// GIF-URLs für die Auflösung. Werden nach Antwort zufällig gezogen.
// Tipp: einfach neue Giphy-URLs in das passende Array einfügen.
// Format: stabile Giphy-CDN-URLs (https://media.giphy.com/media/<id>/giphy.gif)
// Alle URLs hier wurden geprüft (HTTP 200, weltweit erreichbar).

module.exports = {
  CORRECT_GIFS: [
    "https://media.giphy.com/media/3o7TKr3nzbh5WgCFxe/giphy.gif",
    "https://media.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif",
    "https://media.giphy.com/media/g9582DNuQppxC/giphy.gif",
    "https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif",
    "https://media.giphy.com/media/3o7abAHdYvZdBNnGZq/giphy.gif",
    "https://media.giphy.com/media/3o6Zt6ML6BklcajjsA/giphy.gif",
    "https://media.giphy.com/media/oGzFZek2lszyU/giphy.gif",
    "https://media.giphy.com/media/dYZuqJLDVsCXm/giphy.gif",
    "https://media.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif",
    "https://media.giphy.com/media/Zw3oBUuOlDJ3W/giphy.gif",
    "https://media.giphy.com/media/cMNtarVangsf6/giphy.gif",
    "https://media.giphy.com/media/3og0IPxMM0erATueVW/giphy.gif",
    "https://media.giphy.com/media/26gJzMcgzqfx2u8mc/giphy.gif",
    "https://media.giphy.com/media/l4FGHQHmRiVo6CCMU/giphy.gif",
    "https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif",
    "https://media.giphy.com/media/l3vR85PnGsBwu1PFK/giphy.gif",
    "https://media.giphy.com/media/3o6gE6LqxxtqJqnAru/giphy.gif",
    "https://media.giphy.com/media/3oFzm1pE1vQTrU0VRC/giphy.gif",
    "https://media.giphy.com/media/13EjjLAEv4lKmI/giphy.gif",
    "https://media.giphy.com/media/11sBLVxNs7v6WA/giphy.gif",
    "https://media.giphy.com/media/l4Ki4XGCSO33TpvMc/giphy.gif",
    "https://media.giphy.com/media/9DfYUx2NQHoAhJVwoP/giphy.gif",
    "https://media.giphy.com/media/RkPZTPNiLvep6/giphy.gif",
    "https://media.giphy.com/media/c2YyNySJ1CbFC/giphy.gif",
    "https://media.giphy.com/media/cI0sxPdsKxBwc/giphy.gif",
    "https://media.giphy.com/media/JltOMwYmi0VrO/giphy.gif",
    "https://media.giphy.com/media/12msLqxlVZjyfm/giphy.gif",
    "https://media.giphy.com/media/3o7TKMt1VVNkHV2PaE/giphy.gif"
  ],
  WRONG_GIFS: [
    "https://media.giphy.com/media/3o7TKsQ8gqVrxZZUw0/giphy.gif",
    "https://media.giphy.com/media/l4FGuhL4U2WyjdkaY/giphy.gif",
    "https://media.giphy.com/media/26gsspfbuhqdpwxva/giphy.gif",
    "https://media.giphy.com/media/14ut8PhnIwzros/giphy.gif",
    "https://media.giphy.com/media/QMHoU66sBXqqLqYvGO/giphy.gif",
    "https://media.giphy.com/media/d10dMmzqCYqQ0/giphy.gif",
    "https://media.giphy.com/media/wXrHYKdIp8WUE/giphy.gif",
    "https://media.giphy.com/media/Y3VnXtJ9GR0Wc/giphy.gif",
    "https://media.giphy.com/media/jjT7n0oXtyQuY/giphy.gif",
    "https://media.giphy.com/media/3oEjI4dWB4hp0bkayY/giphy.gif",
    "https://media.giphy.com/media/MdA1uqddfR53e/giphy.gif",
    "https://media.giphy.com/media/3og0IO5z8Rd30ktV6g/giphy.gif",
    "https://media.giphy.com/media/WxVgbeTKKGaENXnfyW/giphy.gif",
    "https://media.giphy.com/media/3o7btT1T9qpQZWhNlK/giphy.gif",
    "https://media.giphy.com/media/lXiRLB0xy0nhMXIY8/giphy.gif",
    "https://media.giphy.com/media/3o6ZsXbpxTpyWgNzm0/giphy.gif",
    "https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif",
    "https://media.giphy.com/media/3oz8xLd9DJq2l2VFtu/giphy.gif",
    "https://media.giphy.com/media/QBd2kLB5qDmysEXre9/giphy.gif",
    "https://media.giphy.com/media/26FPGwvShc0OqQUjK/giphy.gif",
    "https://media.giphy.com/media/6uMqzcbWRhoT6/giphy.gif",
    "https://media.giphy.com/media/3oz8xRD6cAa2t5dEo0/giphy.gif",
    "https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif",
    "https://media.giphy.com/media/3oEdv3Dj6j3VuwGDpu/giphy.gif",
    "https://media.giphy.com/media/26FmRLBRZfpMNwWdy/giphy.gif",
    "https://media.giphy.com/media/9Y5BbDSkSTiY8/giphy.gif",
    "https://media.giphy.com/media/8vQSQ3cNXuDGo/giphy.gif",
    "https://media.giphy.com/media/dpfeniRTZ9V20/giphy.gif",
    "https://media.giphy.com/media/cKlMwGOcbmaJq/giphy.gif",
    "https://media.giphy.com/media/zaqclXyLz3Uoo/giphy.gif"
  ]
};
